# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import services.keypoints_detection.grpc_files.keypoints_detection_pb2 as keypoints__detection__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in keypoints_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class YOLOKeypointsDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectKeypoints = channel.stream_stream(
                '/yolo.keypoints_detection.YOLOKeypointsDetectionService/DetectKeypoints',
                request_serializer=keypoints__detection__pb2.Frame.SerializeToString,
                response_deserializer=keypoints__detection__pb2.KeypointsDetectionResponse.FromString,
                _registered_method=True)


class YOLOKeypointsDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectKeypoints(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YOLOKeypointsDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectKeypoints': grpc.stream_stream_rpc_method_handler(
                    servicer.DetectKeypoints,
                    request_deserializer=keypoints__detection__pb2.Frame.FromString,
                    response_serializer=keypoints__detection__pb2.KeypointsDetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yolo.keypoints_detection.YOLOKeypointsDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'yolo.keypoints_detection.YOLOKeypointsDetectionService',
        rpc_method_handlers
    )


 # This class is part of an EXPERIMENTAL API.
class YOLOKeypointsDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectKeypoints(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/yolo.keypoints_detection.YOLOKeypointsDetectionService/DetectKeypoints',
            keypoints__detection__pb2.Frame.SerializeToString,
            keypoints__detection__pb2.KeypointsDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
