# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: keypoints_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'keypoints_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19keypoints_detection.proto\x12\x18yolo.keypoints_detection\"*\n\x05\x46rame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\x9b\x01\n\x1aKeypointsDetectionResponse\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12\x34\n\x05\x62oxes\x18\x02 \x03(\x0b\x32%.yolo.keypoints_detection.BoundingBox\x12\x35\n\tkeypoints\x18\x03 \x03(\x0b\x32\".yolo.keypoints_detection.Keypoint\"n\n\x0b\x42oundingBox\x12\x0c\n\x04x1_n\x18\x01 \x01(\x02\x12\x0c\n\x04y1_n\x18\x02 \x01(\x02\x12\x0c\n\x04x2_n\x18\x03 \x01(\x02\x12\x0c\n\x04y2_n\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x13\n\x0b\x63lass_label\x18\x06 \x01(\t\"4\n\x08Keypoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x32\x8d\x01\n\x1dYOLOKeypointsDetectionService\x12l\n\x0f\x44\x65tectKeypoints\x12\x1f.yolo.keypoints_detection.Frame\x1a\x34.yolo.keypoints_detection.KeypointsDetectionResponse(\x01\x30\x01\x62\x06proto3') # noqa

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keypoints_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=55
  _globals['_FRAME']._serialized_end=97
  _globals['_KEYPOINTSDETECTIONRESPONSE']._serialized_start=100
  _globals['_KEYPOINTSDETECTIONRESPONSE']._serialized_end=255
  _globals['_BOUNDINGBOX']._serialized_start=257
  _globals['_BOUNDINGBOX']._serialized_end=367
  _globals['_KEYPOINT']._serialized_start=369
  _globals['_KEYPOINT']._serialized_end=421
  _globals['_YOLOKEYPOINTSDETECTIONSERVICE']._serialized_start=424
  _globals['_YOLOKEYPOINTSDETECTIONSERVICE']._serialized_end=565
# @@protoc_insertion_point(module_scope)
