# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ball_inference.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "ball_inference.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14\x62\x61ll_inference.proto\x12\x13yolo.ball_detection"*\n\x05\x46rame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c"Z\n\x15\x42\x61llInferenceResponse\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12/\n\x05\x62oxes\x18\x02 \x03(\x0b\x32 .yolo.ball_detection.BoundingBox"n\n\x0b\x42oundingBox\x12\x0c\n\x04x1_n\x18\x01 \x01(\x02\x12\x0c\n\x04y1_n\x18\x02 \x01(\x02\x12\x0c\n\x04x2_n\x18\x03 \x01(\x02\x12\x0c\n\x04y2_n\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x13\n\x0b\x63lass_label\x18\x06 \x01(\t2w\n\x18YOLOBallInferenceService\x12[\n\rInferenceBall\x12\x1a.yolo.ball_detection.Frame\x1a*.yolo.ball_detection.BallInferenceResponse(\x01\x30\x01\x62\x06proto3'  # noqa
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ball_inference_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FRAME"]._serialized_start = 45
    _globals["_FRAME"]._serialized_end = 87
    _globals["_BALLINFERENCERESPONSE"]._serialized_start = 89
    _globals["_BALLINFERENCERESPONSE"]._serialized_end = 179
    _globals["_BOUNDINGBOX"]._serialized_start = 181
    _globals["_BOUNDINGBOX"]._serialized_end = 291
    _globals["_YOLOBALLINFERENCESERVICE"]._serialized_start = 293
    _globals["_YOLOBALLINFERENCESERVICE"]._serialized_end = 412
# @@protoc_insertion_point(module_scope)
